############################ Default configuration #########################
baseURL = "https://examplesite.com/"
languageCode = "en-us"
# site title 
title = "Nacionalna raziskava o razširjenosti bolezni COVID-19 v Sloveniji0"
# theme
theme = "northendlab"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[params.css]
link = "plugins/user.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"


########################### Navigation ###################################

# footer menu
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1

[[menu.footer]]
URL = "tools"
name = "tools"
weight = 2


######################### Default Parameters ###########################
[params]
# home
home = "Home"
# logo
logo = "images/logo.svg"
# meta data
author = "Themefisher"
description = "This is meta description"
# google tag manager
google_tag_manager = "" # your id
# google analitycs ID
google_analitycs_id = "" # your id
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
copyright = "&copy; Spletno stran vzdržujejo in informacijsko-analitično podporo nudijo sodelavci iz [Biolaba](https://fri.uni-lj.si/en/laboratory/biolab) na [UL FRI](https://www.fri.uni-lj.si/sl) – razvijalci programa za podatkovno rudarjenje [Orange](https://orange.biolab.si/). Ljubljana, 2020."
# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# search
[params.search]
enable = true


####################### banner #######################################
[params.banner]
bgImage = "images/banner/banner-bg.svg"
povabljeniPrebivalci = "3000"
sprejetaPovabila = "1283"
odvzetihVzorcev = "568"
dateHour = "20. 4. 2020 ob 16.30"
image = "images/banner/illustration.svg"


[params.opis]
text = "Na reprezentativnem vzorcu nekaj tisoč prebivalcev bomo po vsej Sloveniji opravili testiranja o razširjenosti novega koronavirusa v populaciji. Z raziskavo bi želeli ugotoviti, koliko prebivalcev je okužbo prebolelo. Raziskavo je podprlo [Ministrstvo za zdravje](https://www.gov.si/drzavni-organi/ministrstva/ministrstvo-za-zdravje/) in [Vlada Republike Slovenije](https://www.gov.si/drzavni-organi/vlada/), vodi pa jo [Inštitut za mikrobiologijo Medicinske fakultete Univerze v Ljubljani.](http://www.imi.si)"


######################## Logos ###############################
[params.imi]
img = "images/logos/imi.png"
link = "http://www.imi.si"
[[params.logos]]
img = "images/logos/fri.png"
link = "https://www.fri.uni-lj.si/sl"
[[params.logos]]
img = "images/logos/nmp.png"
link = "https://www.facebook.com/NMPSlovenija/"
[[params.logos]]
img = "images/logos/surs.png"
link = "https://www.stat.si/"
[[params.logos]]
img = "images/logos/fdv.jpg"
link = "https://www.fdv.uni-lj.si/"


############################## Social Site ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
link = "#"