name: Statistics update

# Note: https://crontab.guru/#*/15_*_*_*_*
on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  update_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade requests

      - name: Create local changes
        run: python3 update_script.py ${{ secrets.SERVER_URL }} ${{ secrets.API_TOKEN }}

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Auto-update statistics" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
